server.port=8080
spring.application.name=main-service

stats-server.url=${STATS_SERVER_URL:http://localhost:9090}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ewm_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ewm_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.sql.init.mode=always

logging.level.root=INFO
logging.level.ru.practicum=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# ?????? ??? ? JSON
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

# ?????? ??? ? ?????????? ??????? (query parameters)
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss